---
- hosts: all
  sudo: True
  tasks: 
    - name: copy files to /usr/local/bin
      copy:
        src: "{{ item }}"
        dest: /usr/local/bin/
        owner: root
        mode: 0555
      with_fileglob:
        - files/bin/*
    - name: copy files to /usr/local/sbin
      copy:
        src: "{{ item }}"
        dest: /usr/local/sbin/
        owner: root
        mode: 0555
      with_fileglob:
        - files/sbin/*
    - name: copy perl scripts to /usr/lib/cgi-bin/sites/
      copy:
        src: "{{ item }}"
        dest: /usr/lib/cgi-bin/sites/
        owner: root
        mode: 0755
      with_fileglob:
        - files/www/*.pl
    - name: copy script templates to /usr/lib/cgi-bin/sites/
      copy:
        src: "{{ item }}"
        dest: /usr/lib/cgi-bin/sites/
        owner: root
        mode: 0644
      with_fileglob:
        - files/www/*.tt
