--- 
- 
  handlers: 
    - 
      name: "restart apache"
      service: "name=apache2 state=restarted"
    - 
      name: "restart apache"
      service: "name=apache2 state=restarted"
    -
      name: "install koha git config"
      copy: 
        dest: /usr/local/src/koha/.git/config
        mode: 365
        owner: root
        src: files/git/config
      notify:
        - "update koha git repo"
    -
      name: "update koha git repo"
      command: cd /usr/local/src/koha && yes | git fetch --all
  hosts: all
  sudo: true
  tasks: 
    - name: "Clone koha source to /usr/local/src/koha"
      git:
        repo: git://git.koha-community.org/koha.git
        dest: /usr/local/src/koha
        accept_hostkey: yes
      notify: 
        - "install koha git config"
    - name: "install sshfs"
      apt:
        name: sshfs
        state: present
        update_cache: yes
    - name: "install fuse"
      apt:
        name: fuse
        state: present
        update_cache: yes
    - 
      copy: 
        dest: /usr/local/bin/
        mode: 365
        owner: root
        src: "{{ item }}"
      name: "copy files to /usr/local/bin"
      with_fileglob: 
        - files/bin/*
    - 
      copy: 
        dest: /usr/local/sbin/
        mode: 365
        owner: root
        src: "{{ item }}"
      name: "copy files to /usr/local/sbin"
      with_fileglob: 
        - files/sbin/*
    - 
      copy: 
        dest: /usr/lib/cgi-bin/sites/
        mode: 493
        owner: root
        src: "{{ item }}"
      name: "copy perl scripts to /usr/lib/cgi-bin/sites/"
      with_fileglob: 
        - files/www/*.pl
    - 
      copy: 
        dest: /usr/lib/cgi-bin/sites/
        mode: 420
        owner: root
        src: "{{ item }}"
      name: "copy script templates to /usr/lib/cgi-bin/sites/"
      with_fileglob: 
        - files/www/*.tt
    - 
      copy: 
        dest: /etc/apache2/sites-available/000-bwsdev
        mode: 420
        owner: root
        src: files/apache/000-bwsdev
      name: "copy apache conf file to /etc/apache2/sites-available/"
      notify: 
        - "restart apache"
    - 
      file: 
        dest: /etc/apache2/sites-enabled/000-bwsdev
        src: /etc/apache2/sites-available/000-bwsdev
        state: link
      name: "symlink apache to /etc/apache2/sites-enabled"
      notify: 
        - "restart apache"

