---
- hosts: all
  sudo: True
  tasks: 
    - name: copy files to /usr/local/bin
      copy:
        src: "{{ item }}"
        dest: /usr/local/bin/
        owner: root
        mode: 0555
      with_fileglob:
        - files/bin/*
    - name: copy files to /usr/local/sbin
      copy:
        src: "{{ item }}"
        dest: /usr/local/sbin/
        owner: root
        mode: 0555
      with_fileglob:
        - files/sbin/*
    - name: copy perl scripts to /usr/lib/cgi-bin/sites/
      copy:
        src: "{{ item }}"
        dest: /usr/lib/cgi-bin/sites/
        owner: root
        mode: 0755
      with_fileglob:
        - files/www/*.pl
    - name: copy script templates to /usr/lib/cgi-bin/sites/
      copy:
        src: "{{ item }}"
        dest: /usr/lib/cgi-bin/sites/
        owner: root
        mode: 0644
      with_fileglob:
        - files/www/*.tt
    - name: copy apache conf file to /etc/apache2/sites-available/ 
      copy:
        src: files/apache/000-bwsdev
        dest: /etc/apache2/sites-available/000-bwsdev
        owner: root
        mode: 0644
      notify:
        - restart apache
    - name: symlink apache to /etc/apache2/sites-enabled
      file:
        src: /etc/apache2/sites-available/000-bwsdev
        dest: /etc/apache2/sites-enabled/000-bwsdev
        state: link
      notify:
        - restart apache
  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
