# Default configuration values
---
DB_HOSTNAME: "db"
EDITOR: "vim"
KOHA_DB_PASSWORD: "KohaPass"
KOHA_DOMAIN: ".myDNSname.org"
KOHA_INTRANET_PORT: "8081"
KOHA_INTRANET_PREFIX: "staff-"
KOHA_INTRANET_SUFFIX: ""
KOHA_MARC_FLAVOUR: "marc21"
KOHA_OPAC_PORT: "8080"
KOHA_OPAC_PREFIX: ""
KOHA_OPAC_SUFFIX: ""
KOHA_PASS: "koha"
KOHA_PROVE_CPUS: ""
KOHA_USER: "koha"
PERL5LIB: "/kohadevbox/koha:/kohadevbox/qa-test-tools"
REMOTE_DEBUGGER_DIR: ""
REMOTE_DEBUGGER_KEY: ""
REMOTE_DEBUGGER_LOCATION: ""
REMOTE_DEBUGGER_PACKAGE: ""
RUN_TESTS_AND_EXIT: "no"
DB_ROOT_PASSWORD: "Hey!CanYouLetMeIn?Thanks!"
