---
-
  hosts: all
  become: true

  handlers:
    - name: "Restart apache"
      service: "name=apache2 state=restarted"

    - name: "Install koha git config"
      copy:
        dest: /usr/local/src/koha/.git/config
        mode: 365
        owner: root
        src: files/git/config
      notify:
        - "Update koha git repo"

    - name: "Update koha git repo"
      shell: "cd /usr/local/src/koha && yes | git fetch --all && git pull"

    - name: "Update koha-testing-docker git rep"
      shell: "cd /usr/local/src/koha-testing-docker && yes | git fetch --all && git pull"

    - name: "Update koha git repo for sandbox"
      shell: "cd /usr/local/src/koha-sandboxes/{{ KOHA_INSTANCE }} && yes | git fetch --all && git pull"

    - name: "Restart plack in docker container"
      delegate_to: "koha-{{ KOHA_INSTANCE }}"
      shell: "koha-plack --restart {{ KOHA_INSTANCE }}"

    - name: "Run updatedatabase.pl in docker container"
      delegate_to: "koha-{{ KOHA_INSTANCE }}"
      shell: "koha-shell -c '/kohadevbox/koha/installer/data/mysql/updatedatabase.pl' {{ KOHA_INSTANCE }}"

  vars_files:
      - vars/defaults.yml
      - vars/user.yml
      - "{{ env_file }}"

  tasks:
    - debug:
        msg: "Using '{{ KOHA_INSTANCE }}' as instance name"

    - name: "Clone koha source to /usr/local/src/koha"
      git:
        repo: git://git.koha-community.org/koha.git
        dest: /usr/local/src/koha
        accept_hostkey: yes
        update: yes
      notify:
        - "Install koha git config"

    - name: "Copy source koha clone for sandbox"
      shell: "[ -d /usr/local/src/koha-sandboxes/{{ KOHA_INSTANCE }} ] || git clone -l -s --progress /usr/local/src/koha /usr/local/src/koha-sandboxes/{{ KOHA_INSTANCE }}"
      ignore_errors: yes

    - name: Create a new database for Koha instance
      mysql_db:
        name: "koha_{{ KOHA_INSTANCE }}"
        state: present
        login_host: 127.0.0.1
        login_port: 3306
        login_user: root
        login_password: "{{ DB_ROOT_PASSWORD }}"

    - mysql_user:
        name: "koha_{{ KOHA_INSTANCE }}"
        password: "{{ KOHA_DB_PASSWORD }}"
        priv: 'koha_{{ KOHA_INSTANCE }}.*:ALL'
        host: '%'
        state: present
        login_host: 127.0.0.1
        login_port: 3306
        login_user: root
        login_password: "{{ DB_ROOT_PASSWORD }}"

    - name: "Install koha git config for sandbox"
      copy:
        dest: /usr/local/src/koha-sandboxes/{{ KOHA_INSTANCE }}/.git/config
        mode: 365
        owner: root
        src: files/git/config
      notify:
        - "Update koha git repo for sandbox"

    - name: Start new koha-testing-docker container
      docker_container:
        name: "koha-{{ KOHA_INSTANCE }}"
        state: present
        image: koha/koha-testing:master
        pull: yes
        restart: yes
        restart_policy: always
        state: started
        privileged: yes
        networks:
          - name: kohanet
        published_ports:
          - 8080
          - 8081
          - 22
        env:
            DB_HOSTNAME: "{{ DB_HOSTNAME }}"
            EDITOR: "{{ EDITOR }}"
            GIT_BZ_PASSWORD: "{{ GIT_BZ_PASSWORD }}"
            GIT_BZ_USER: "{{ GIT_BZ_USER }}"
            GIT_USER_EMAIL: "{{ GIT_USER_EMAIL }}"
            GIT_USER_NAME: "{{ GIT_USER_NAME }}"
            KOHA_CONF: "{{ KOHA_CONF }}"
            KOHA_DB_PASSWORD: "{{ KOHA_DB_PASSWORD }}"
            KOHA_DOMAIN: "{{ KOHA_DOMAIN }}"
            KOHA_INSTANCE: "{{ KOHA_INSTANCE }}"
            KOHA_INTRANET_PORT: "{{ KOHA_INTRANET_PORT }}"
            KOHA_INTRANET_PREFIX: "{{ KOHA_INTRANET_PREFIX }}"
            KOHA_INTRANET_SUFFIX: "{{ KOHA_INTRANET_SUFFIX }}"
            KOHA_MARC_FLAVOUR: "{{ KOHA_MARC_FLAVOUR }}"
            KOHA_OPAC_PORT: "{{ KOHA_OPAC_PORT }}"
            KOHA_OPAC_PREFIX: "{{ KOHA_OPAC_PREFIX }}"
            KOHA_OPAC_SUFFIX: "{{ KOHA_OPAC_SUFFIX }}"
            KOHA_PASS: "{{ KOHA_PASS }}"
            KOHA_PROVE_CPUS: "{{ KOHA_PROVE_CPUS }}"
            KOHA_USER: "{{ KOHA_USER }}"
            PERL5LIB: "{{ PERL5LIB }}"
            #REMOTE_DEBUGGER_DIR: "{{ REMOTE_DEBUGGER_DIR }}"
            #REMOTE_DEBUGGER_KEY: "{{ REMOTE_DEBUGGER_KEY }}"
            #REMOTE_DEBUGGER_LOCATION: "{{ REMOTE_DEBUGGER_LOCATION }}"
            #REMOTE_DEBUGGER_PACKAGE: "{{ REMOTE_DEBUGGER_PACKAGE }}"
            RUN_TESTS_AND_EXIT: "{{ RUN_TESTS_AND_EXIT }}"
        volumes:
          - /usr/local/src/koha-sandboxes/{{ KOHA_INSTANCE }}:/kohadevbox/koha
          - /usr/local/src/koha:/usr/local/src/koha

    - name: "Get host port for sandbox staff port"
      shell: docker port koha-{{ KOHA_INSTANCE }} | grep 8081 | rev | cut -d":" -f1 | rev
      register: docker_port_intranet
    - debug:
        msg: "Using '{{ docker_port_intranet.stdout }}' as staff port"
    - name: "Get host port for sandbox opac port"
      shell: docker port koha-{{ KOHA_INSTANCE }} | grep 8080 | rev | cut -d":" -f1 | rev
      register: docker_port_opac
    - debug:
        msg: "Using '{{ docker_port_opac.stdout }}' as opac port"
    - name: "Get host port for sandbox ssh port"
      shell: docker port koha-{{ KOHA_INSTANCE }} | grep 8080 | rev | cut -d":" -f1 | rev
      register: docker_port_ssh
    - debug:
        msg: "Using '{{ docker_port_ssh.stdout }}' as ssh port"

    - name: "Install apache config for sandbox instance"
      template:
        src: templates/sandbox_instance.conf.j2
        dest: /etc/apache2/sites-available/{{ KOHA_INSTANCE }}.conf
      notify: "Restart apache"

    - name: "Symlink the new apache config from sites-available to sites-enabled"
      file:
        src: /etc/apache2/sites-available/{{ KOHA_INSTANCE }}.conf
        dest: /etc/apache2/sites-enabled/{{ KOHA_INSTANCE }}.conf
        owner: root
        group: root
        state: link
      notify: "Restart apache"

    - name: "Will apply bug number {{ BUG_NUMBER }} in 1 minute"
      pause:
        minutes: 1
      when: not( (BUG_NUMBER is undefined) or (BUG_NUMBER is none) or (BUG_NUMBER | trim == '') )
    - name: "Add docker container koha-{{ KOHA_INSTANCE }} to ansible hosts"
      add_host:
        name: "koha-{{ KOHA_INSTANCE }}"
        groups: koha
        ansible_connection: docker
      changed_when: false
    - name: "Apply bug {{ BUG_NUMBER }} via git-bz in docker container"
      delegate_to: "koha-{{ KOHA_INSTANCE }}"
      shell: "cd /kohadevbox/koha && yes | git bz apply {{ BUG_NUMBER }}"
      when: not( (BUG_NUMBER is undefined) or (BUG_NUMBER is none) or (BUG_NUMBER | trim == '') )
      ignore_errors: no
      notify:
        - "Restart plack in docker container"
        - "Run updatedatabase.pl in docker container"

    - name: "Install OpenSSH Server"
      delegate_to: "koha-{{ KOHA_INSTANCE }}"
      apt:
        name: openssh-server
        update_cache: yes
        state: present
      ignore_errors: yes
    - name: "Enable PermitRootLogin for sshd"
      delegate_to: "koha-{{ KOHA_INSTANCE }}"
      shell: "echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config"
    - name: "Start sshd"
      delegate_to: "koha-{{ KOHA_INSTANCE }}"
      shell: "/etc/init.d/ssh start"
      # Service module fails to start ssh and I don't know why
    - name: Set root password to 'koha'
      delegate_to: "koha-{{ KOHA_INSTANCE }}"
      user:
        name: root
        password: "{{ 'koha' | password_hash('sha512') }}"

    - name: "Pause for koha container to set itself up, before applying git remote {{ GIT_REMOTE }} and branch {{ GIT_BRANCH }}"
      pause:
        minutes: 1
      when: ( (BUG_NUMBER is undefined) or (BUG_NUMBER is none) or (BUG_NUMBER | trim == '') )
    - name: "Add docker container koha-{{ KOHA_INSTANCE }} to ansible hosts"
      add_host:
        name: "koha-{{ KOHA_INSTANCE }}"
        groups: koha
        ansible_connection: docker
      changed_when: false
    - name: "Add git remote {{ GIT_REMOTE }} as {{ KOHA_INSTANCE }}"
      delegate_to: "koha-{{ KOHA_INSTANCE }}"
      shell: "cd /kohadevbox/koha && git remote add {{ KOHA_INSTANCE }} {{ GIT_REMOTE }} && git fetch {{ KOHA_INSTANCE }} && git checkout {{ KOHA_INSTANCE }}/{{ GIT_BRANCH }}"
      when: not( (GIT_REMOTE is undefined) or (GIT_REMOTE is none) or (GIT_REMOTE | trim == '') and not(GIT_BRANCH is undefined) or (GIT_BRANCH is none) or (GIT_BRANCH | trim == '') )
      ignore_errors: yes
      notify:
        - "Restart plack in docker container"
        - "Run updatedatabase.pl in docker container"

    - name: "Index the records for the first time"
      delegate_to: "koha-{{ KOHA_INSTANCE }}"
      shell: "koha-rebuild-zebra -f -a -b -v {{ KOHA_INSTANCE }}"
      ignore_errors: yes
    - name: "Restart Zebra after indexing records"
      delegate_to: "koha-{{ KOHA_INSTANCE }}"
      shell: "koha-zebra --restart {{ KOHA_INSTANCE }}"
      ignore_errors: yes
    - name: "Restart Plack after indexing records"
      delegate_to: "koha-{{ KOHA_INSTANCE }}"
      shell: "koha-plack --restart {{ KOHA_INSTANCE }}"
      ignore_errors: yes

    - name: "Restart apache, one last time"
      service: "name=apache2 state=restarted"
