---
-
  handlers:
    -
      name: "Restart apache"
      service: "name=apache2 state=restarted"
    -
      name: "Enable apache site"
      shell: a2ensite {{ instance_name }}
      notify:
        - "Restart apache"
    -
      name: "Install koha git config"
      copy:
        dest: /usr/local/src/koha/.git/config
        mode: 365
        owner: root
        src: files/git/config
      notify:
        - "Update koha git repo"
    -
      name: "Update koha git repo"
      shell: "cd /usr/local/src/koha && yes | git fetch --all"
    -
      name: "Update koha git repo for sandbox"
      shell: "cd /usr/local/src/koha-sandboxes/{{ instance_name }} && yes | git fetch --all"

  hosts: all
  become: true

  tasks:
    - debug:
        msg: "Using '{{ instance_name }}' as instance name"

    - name: "Clone koha source to /usr/local/src/koha"
      git:
        repo: git://git.koha-community.org/koha.git
        dest: /usr/local/src/koha
        accept_hostkey: yes
        update: yes
      notify:
        - "Install koha git config"

    - name: "Copy source koha clone for sandbox"
      shell: "[ -d /usr/local/src/koha-sandboxes/{{ instance_name }} ] || git clone -l -s --progress /usr/local/src/koha /usr/local/src/koha-sandboxes/{{ instance_name }}"
      ignore_errors: yes

    - name: Create a new database for Koha instance
      mysql_db:
        name: "koha_{{ instance_name }}"
        state: present
        login_host: 127.0.0.1
        login_port: 3306
        login_user: root
        login_password: password

    - mysql_user:
        name: "koha_{{ instance_name }}"
        password: password
        priv: 'koha_{{ instance_name }}.*:ALL'
        host: '%'
        state: present
        login_host: 127.0.0.1
        login_port: 3306
        login_user: root
        login_password: password

    - name: "Install koha git config for sandbox"
      copy:
        dest: /usr/local/src/koha-sandboxes/{{ instance_name }}/.git/config
        mode: 365
        owner: root
        src: files/git/config
      notify:
        - "Update koha git repo for sandbox"

    - name: Start new koha-testing-docker container
      docker_container:
        name: "koha-{{ instance_name }}"
        state: present
        image: koha/koha-testing:master
        pull: yes
        restart: yes
        restart_policy: always
        state: started
        networks:
          - name: kohanet
        published_ports:
          - 8080
          - 8081
        env:
            DB_HOSTNAME: db
            EDITOR: vim
            GIT_BZ_PASSWORD: nothing
            GIT_BZ_USER: me@example.com
            GIT_USER_EMAIL: me@example.com
            GIT_USER_NAME: John Doe
            KOHA_CONF: /etc/koha/sites/kohadev/koha-conf.xml
            KOHA_DB_PASSWORD: password
            KOHA_DOMAIN: .myDNSname.org
            KOHA_INSTANCE: "{{ instance_name }}"
            KOHA_INTRANET_PORT: 8081
            KOHA_INTRANET_PREFIX:
            KOHA_INTRANET_SUFFIX: -intra
            KOHA_MARC_FLAVOUR: marc21
            KOHA_OPAC_PORT: 8080
            KOHA_OPAC_PREFIX:
            KOHA_OPAC_SUFFIX:
            KOHA_PASS: koha
            KOHA_PROVE_CPUS:
            KOHA_USER: koha
            PERL5LIB: /kohadevbox/koha:/kohadevbox/qa-test-tools
            REMOTE_DEBUGGER_DIR:
            REMOTE_DEBUGGER_KEY:
            REMOTE_DEBUGGER_LOCATION:
            REMOTE_DEBUGGER_PACKAGE:
            RUN_TESTS_AND_EXIT: no
        volumes:
          - /usr/local/src/koha-sandboxes/{{ instance_name }}:/kohadevbox/koha

    - name: "Get host port for sandbox staff port"
      shell: docker port koha-{{ instance_name }} | grep 8081 | rev | cut -d":" -f1 | rev
      register: docker_port_intranet
    - debug:
        msg: "Using '{{ docker_port_intranet.stdout }}' as staff port"
    - name: "Get host port for sandbox opac port"
      shell: docker port koha-{{ instance_name }} | grep 8080 | rev | cut -d":" -f1 | rev
      register: docker_port_opac
    - debug:
        msg: "Using '{{ docker_port_opac.stdout }}' as opac port"

    - name: "Install apache config for sandbox instance"
      template:
        src: templates/sandbox_instance.conf.j2
        dest: /etc/apache2/sites-available/{{ instance_name }}.conf
      notify: "Enable apache site"
