---
-
  hosts: all
  become: true

  handlers:
    -
      name: "Restart apache"
      service: "name=apache2 state=restarted"

  vars_files:
      - vars/defaults.yml
      - vars/user.yml
      - "{{ env_file }}"

  tasks:
    - debug:
        msg: "Using '{{ KOHA_INSTANCE }}' as instance name"

    - name: Remove koha-testing-docker container
      docker_container:
        name: "koha-{{ KOHA_INSTANCE }}"
        state: absent
        force_kill: yes

    - name: Delete database for Koha instance
      mysql_db:
        name: "koha_{{ KOHA_INSTANCE }}"
        state: absent
        login_host: 127.0.0.1
        login_port: 3306
        login_user: root
        login_password: "{{ DB_ROOT_PASSWORD }}"

    - name: Delete database user for Koha instnace
      mysql_user:
        name: "koha_{{ KOHA_INSTANCE }}"
        state: absent
        host: '%'
        login_host: 127.0.0.1
        login_port: 3306
        login_user: root
        login_password: "{{ DB_ROOT_PASSWORD }}"

    - name: "Delete sandbox instance koha git clone"
      file:
        path: /usr/local/src/koha-sandboxes/{{ KOHA_INSTANCE }}
        state: absent

    - name: "Remove apache config symlink for sandbox instance"
      file:
        path: /etc/apache2/sites-enabled/{{ KOHA_INSTANCE }}.conf
        state: absent
      notify: "Restart apache"

    - name: "Remove apache config for sandbox instance"
      file:
        path: /etc/apache2/sites-available/{{ KOHA_INSTANCE }}.conf
        state: absent
      notify: "Restart apache"

    - name: "Restart apache, one last time"
      service: "name=apache2 state=restarted"
