---
-
  hosts: all
  become: true

  handlers:
    -
      name: "Restart apache"
      service: "name=apache2 state=restarted"

  tasks:
    - debug:
        msg: "Using '{{ instance_name }}' as instance name"

    - name: Remove koha-testing-docker container
      docker_container:
        name: "koha-{{ instance_name }}"
        state: absent
        force_kill: yes

    - name: "Delete sandbox instance koha git clone"
      file:
        path: /usr/local/src/koha-sandboxes/{{ instance_name }}
        state: absent

    - name: "Remove apache config for sandbox instance"
      file:
        path: /etc/apache2/sites-enabled/{{ instance_name }}.conf
        state: absent
      notify: "Restart apache"
